mah9/Controllers/VideoController.cs
using mah9.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mah9.Controllers
{
    public class VideoController : Controller
    {

        Models.ApplicationDbContext context;
        private ApplicationDbContext db = new ApplicationDbContext();

        public VideoController()
        {
            context = new ApplicationDbContext();
        }

        public ActionResult Index()
        {
            ViewBag.ClassName = new SelectList(context.Class_.ToList(), "ClassName", "ClassName");
            // string n = "Math";
            var videos = context.Video_.ToList();
            // ViewBag.UserID = HttpContext.User.Identity.GetUserId();
            return View(videos);


        }
        //GET
        public ActionResult Watch(int id)
        {
            var r = context.Video_.SingleOrDefault(x => x.VideoID == id);
            return View(r);
        }

        [HttpPost]
        public ActionResult Watch(VideoModel videos)
        {
           

            return RedirectToAction("Index");
        }



        public ActionResult CreateVideo()
        {
            ViewBag.ClassName = new SelectList(context.Class_.ToList(), "ClassName", "ClassName");
            ViewBag.SubjectName = new SelectList(context.Subject_.ToList(), "subject", "subject");
            var videos = new VideoModel();
            return View(videos);
        }

        [HttpPost]
        public ActionResult CreateVideo(VideoModel videos)
        {
            DateTime date = DateTime.Now;
            videos.Date = date;
            context.Video_.Add(videos);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {

            var r = context.Video_.SingleOrDefault(x => x.VideoID == id);
            return View(r);
        }

        [HttpPost]
        public ActionResult Edit(int id, VideoModel model)
        {
            var v = context.Video_.FirstOrDefault(x => x.VideoID == id);
            v.VideoClass = model.VideoClass;
            v.VideoName = model.VideoName;
            v.VideoSubject = model.VideoSubject;
            v.VideoURL = model.VideoURL;
            
            context.Entry(v).State = EntityState.Modified;
            
            context.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {

            var r = context.Video_.SingleOrDefault(x => x.VideoID == id);
            return View(r);
        }

        [HttpPost]
        public ActionResult Details()
        {





            return RedirectToAction("Index");
        }


        public ActionResult Delete(int id)
        {

            var r = context.Video_.SingleOrDefault(x => x.VideoID == id);
            return View(r);
        }

        [HttpPost]
        public ActionResult Delete(int id, VideoModel model)
        {
            var r = context.Video_.SingleOrDefault(x => x.VideoID == id);

            context.Video_.Remove(r);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        // [HttpPost]
        //  public ActionResult Details_()
        // {




        //   return RedirectToAction("Index");
        // }
    }
}

mah9/Views/Video/CreateVideo.cshtml
@model mah9.Models.VideoModel

@{
    ViewBag.Title = "CreateVideo";
}

<h2>CreateVideo</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>VideoModel</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.VideoName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.VideoName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.VideoName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.VideoURL, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.VideoURL, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.VideoURL, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.VideoClass, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.VideoClass, ViewBag.ClassName as SelectList, "Please Select", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.VideoClass, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.VideoSubject, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.VideoSubject, ViewBag.SubjectName as SelectList, "Please Select", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.VideoSubject, "", new { @class = "text-danger" })
        </div>
    </div>





    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

mah9/Views/Video/Delete.cshtml
@model mah9.Models.VideoModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>VideoModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt style="font-size : large">
            @Html.DisplayNameFor(model => model.VideoID)
        </dt>

        <dd style="font-size : large">
            @Html.DisplayFor(model => model.VideoID)
        </dd>


        <dt style="font-size : large">
            @Html.DisplayNameFor(model => model.VideoName)
        </dt>

        <dd style="font-size : large">
            @Html.DisplayFor(model => model.VideoName)
        </dd>
        <dt style="font-size : large">
            @Html.DisplayNameFor(model => model.VideoURL)
        </dt>

        <dd style="font-size : large">
            @Html.DisplayFor(model => model.VideoURL)
        </dd>
        <dt style="font-size : large">
            @Html.DisplayNameFor(model => model.VideoSubject)
        </dt>

        <dd style="font-size : large">
            @Html.DisplayFor(model => model.VideoSubject)
        </dd>

        <dt style="font-size : large">
            @Html.DisplayNameFor(model => model.VideoClass)
        </dt>

        <dd style="font-size : large">
            @Html.DisplayFor(model => model.VideoClass)
        </dd>

        <dt style="font-size : large">
            @Html.DisplayName("Date of Creation")
        </dt>

        <dd style="font-size : large">
            @Html.DisplayFor(model => model.Date)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="DELETE" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

mah9/Views/Video/Details.cshtml
@model mah9.Models.VideoModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>VideoModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt style="font-size : large">
            @Html.DisplayNameFor(model => model.VideoID)
        </dt>

        <dd style="font-size : large">
            @Html.DisplayFor(model => model.VideoID)
        </dd >


        <dt style="font-size : large">
            @Html.DisplayNameFor(model => model.VideoName)
        </dt >

        <dd style="font-size : large">
            @Html.DisplayFor(model => model.VideoName)
        </dd >
        <dt style="font-size : large">
            @Html.DisplayNameFor(model => model.VideoURL)
        </dt>

        <dd style="font-size : large">
            @Html.DisplayFor(model => model.VideoURL)
        </dd>
        <dt style="font-size : large">
            @Html.DisplayNameFor(model => model.VideoSubject)
        </dt>

        <dd style="font-size : large">
            @Html.DisplayFor(model => model.VideoSubject)
        </dd>

        <dt style="font-size : large">
            @Html.DisplayNameFor(model => model.VideoClass)
        </dt>

        <dd style="font-size : large">
            @Html.DisplayFor(model => model.VideoClass)
        </dd>

        <dt style="font-size : large">
            @Html.DisplayName("Date of Creation")
        </dt>

        <dd style="font-size : large"> 
            @Html.DisplayFor(model => model.Date)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.VideoID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

mah9/Views/Video/Edit.cshtml
@model mah9.Models.VideoModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>VideoModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.VideoID)

        <div class="form-group">
            @Html.LabelFor(model => model.VideoURL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VideoURL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VideoURL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VideoName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VideoName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VideoName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VideoSubject, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VideoSubject, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VideoSubject, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VideoClass, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VideoClass, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VideoClass, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new {style = "display: none;" , @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new {style = "display: none;" , @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new {style = "display: none;" , @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

mah9/Views/Video/Index.cshtml
@model IEnumerable<mah9.Models.VideoModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

    @if (User.IsInRole("Admin") || User.IsInRole("Student"))
    {
        <p>
            @Html.ActionLink("Create New", "CreateVideo", "Video")
        </p>
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.VideoURL)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.VideoName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.VideoSubject)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.VideoClass)
                </th>
                <th>

                </th>
            </tr>

            @foreach (var item in Model)
            {
               
                if (User.IsInRole("Admin"))
                {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.VideoURL)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.VideoName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.VideoSubject)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.VideoClass)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.VideoID }) |
                        @Html.ActionLink("Details", "Details", new { id = item.VideoID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.VideoID })
                    </td>
                </tr>
                }
            }

        </table>

    }

        <head>
            <style>
                .eyad img {
                    border-radius: 25px;
                    transition: 0.3s;
                }

                    .eyad img:hover {
                        transform: scale(1.03,1.03);
                    }
            </style>
        </head>
        <body>

        

            @foreach (var item in ViewBag.ClassName)
            {
                if (User.IsInRole(item.Value) || User.IsInRole("Admin"))
                {

                <h2>@item.Value</h2>
                <hr />
                    foreach (var i in Model)
                    {
                        if (User.IsInRole(i.VideoSubject) || User.IsInRole("Admin"))
                        {
                            if (i.VideoClass == item.Value)
                            {
                    <div class="eyad">
                        <a href="@Url.Action("Watch", "Video", new { id = i.VideoID })" class="elements"><img src="https://vumbnail.com/@i.VideoURL+.jpg" alt="" width="350" height="150"></a>
                    </div>
                            }
                        }
                    }

                }
            }

        </body>

mah9/Views/Video/Watch.cshtml
@model mah9.Models.VideoModel

@{
    ViewBag.Title = "Watch";
}

<h2>@Model.VideoName</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div style="padding:75% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/@Model.VideoURL?h=874ef8bbde&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen style="position:absolute;top:0;left:0;width:100%;height:100%;" title="video0_3.mp4"></iframe></div>
    <script src="https://player.vimeo.com/api/player.js"></script>
    
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>