mah9/Controllers/ClassController.cs
using mah9.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace mah9.Controllers
{
    public class ClassController : Controller
    {

        ApplicationDbContext context;
        private ApplicationUserManager _userManager;

        public ClassController()
        {
            context = new ApplicationDbContext();
        }

        public ClassController(ApplicationUserManager userManager)
        {
            UserManager = userManager;

        }
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        public ActionResult Index()
        {
            var Classes = context.Class_.ToList();
            return View(Classes);
        }

        public ActionResult CreateClass()
        {
            var class1 = new ClassModel();
            return View(class1);
        }

        [HttpPost]
        public ActionResult CreateClass(ClassModel class1, IdentityRole Role)
        {
            class1.OldClassName = class1.ClassName;
            DateTime date = DateTime.Now;
            class1.Date = date;
            context.Class_.Add(class1);
            context.SaveChanges();

            Role.Name = class1.ClassName;
            context.Roles.Add(Role);

            context.SaveChanges();

            return RedirectToAction("Index");
        }

        //GET
        public ActionResult Edit(int id)
        {
            ClassModel model = context.Class_.SingleOrDefault(x => x.ClassID == id);

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(int id, ClassModel model)
        {
            var v = context.Class_.FirstOrDefault(x => x.ClassID == id);
            v.ClassName = model.ClassName;
            v.OldClassName= model.ClassName;
            var r = context.Roles.FirstOrDefault(x => x.Name == model.OldClassName);
            r.Name = model.ClassName;

            var users = context.Users.ToList();
            foreach (var i in users)
            {

                if (await this.UserManager.IsInRoleAsync(i.Id, model.OldClassName) == true)
                {
                    
                    var z = context.Users.FirstOrDefault(x => x.Id == i.Id);
                    z.Class = model.ClassName;
                    context.Entry(z).State = EntityState.Modified;
                }
            }

            context.Entry(r).State = EntityState.Modified;
            context.Entry(v).State = EntityState.Modified;
            context.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            ClassModel model = context.Class_.SingleOrDefault(x => x.ClassID == id);

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(int id, ClassModel model)
        {
            var v = context.Class_.FirstOrDefault(x => x.ClassID == id) ;
            v.ClassName = model.ClassName;
            v.OldClassName = model.ClassName;

            var r = context.Roles.FirstOrDefault(x => x.Name == model.ClassName);

            var users = context.Users.ToList();
            foreach (var i in users)
            {

                if (await this.UserManager.IsInRoleAsync(i.Id, model.ClassName) == true)
                {
                    await this.UserManager.RemoveFromRoleAsync(i.Id, model.ClassName);
                    var z = context.Users.FirstOrDefault(x => x.Id == i.Id);
                    z.Class = "-NULL-";
                    context.Entry(z).State = EntityState.Modified;
                }
            }
            context.Class_.Remove(v);
            context.Roles.Remove(r);

            context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

mah9/Views/Class/CreateClass.cshtml
@model mah9.Models.ClassModel
@{
    ViewBag.Title = "Create Class";
}

<h2>Create Class.</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        



        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ClassName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClassName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClassName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

mah9/Views/Class/Delete.cshtml
@model mah9.Models.ClassModel

@{
    ViewBag.Title = "Delete Class";
}

<h2>Delete Class.</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ClassID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClassID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClassName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClassName)
        </dd>
    </dl>
    <div class="form-group">
        @Html.LabelFor(model => model.ClassID, htmlAttributes: new { style = "display: none;", @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ClassID, new { htmlAttributes = new { style = "display: none;", @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ClassID, "", new { style = "display: none;", @class = "text-danger" })

        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.ClassName, htmlAttributes: new { style = "display: none;", @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ClassName, new { htmlAttributes = new { style = "display: none;", @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ClassName, "", new { style = "display: none;", @class = "text-danger" })

        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.OldClassName, htmlAttributes: new { style = "display: none;", @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OldClassName, new { htmlAttributes = new { style = "display: none;", @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.OldClassName, "", new { style = "display: none;", @class = "text-danger" })

        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="DELETE" class="btn btn-danger" onclick="return confirm('Are you sure you want to DELETE the Class : @Model.ClassName')" />
        </div>
    </div>
</div>


}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

mah9/Views/Class/Edit.cshtml
@model mah9.Models.ClassModel

@{
    ViewBag.Title = "Edit Class";
}

<h2>Edit Class.</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ClassID)

    <div class="form-group">
        @Html.LabelFor(model => model.ClassName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ClassName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ClassName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ClassID, htmlAttributes: new {style = "display: none;", @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ClassID, new { htmlAttributes = new {style = "display: none;", @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ClassID, "", new {style = "display: none;", @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OldClassName, htmlAttributes: new { style = "display: none;",@class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OldClassName, new { htmlAttributes = new { style = "display: none;",@class = "form-control" } })
            @Html.ValidationMessageFor(model => model.OldClassName, "", new {style = "display: none;", @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-success" onclick="return confirm('Are you sure you want to EDIT the Class : @Model.ClassName')" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

mah9/Views/Class/Index.cshtml
@model IEnumerable<mah9.Models.ClassModel>

@{
    ViewBag.Title = "Classes";
}

<h2>Classes List.</h2>

<style type="text/css">


    tr:hover {
        background-color: rgba(196, 196, 196, 0.46);
    }

</style>

<p>
    @Html.ActionLink("Create New Class", "CreateClass", "Class")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ClassName)
        </th>
        <th>

        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ClassName)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ClassID }) |
                
                @Html.ActionLink("Delete", "Delete", new { id = item.ClassID })
            </td>
        </tr>
    }

</table>